---
- name: Server-setup | open necessary ports for control
  ansible.posix.firewalld:
    port: "{{ item }}"
    state: enabled
    permanent: true
  loop:
    - 6443/tcp
    - 2379-2380/tcp
    - 10250/tcp
    - 10259/tcp
    - 10257/tcp
  when: "'control' in group_names"
- name: Server-setup | open necessary ports for workers
  ansible.posix.firewalld:
    service: "{{ item }}"
    state: enabled
    permanent: true
  loop:
    - 10250/tcp
    - 30000-32767/tcp
  when: "'workers' in group_names"
- name: Server-setup | disable swap
  ansible.builtin.command:
    cmd: swapoff -a # noqa: no-changed-when
- name: Server-setup | Comment out the swap line in fstab
  ansible.builtin.lineinfile:
    path: /etc/fstab
    regexp: '^(.+swap.+)'
    backrefs: true
    line: '#\1'
- name: Server-setup | remount all to make sure fstab is correct
  ansible.builtin.command:
    cmd: mount -a # noqa: command-instead-of-module no-changed-when
- name: Server-setup | reboot the server
  ansible.builtin.reboot:
- name: Server-setup | verify that swap is disabled
  ansible.builtin.command:
    cmd: free -h; lsblk; blkid # noqa: no-changed-when
  register: swap_info
- name: Server-setup | display swap verification output
  ansible.builtin.debug:
    msg: "{{ swap_info.stdout_lines }}"
