---
- name: Server-setup | open necessary ports for workers
  ansible.posix.firewalld:
    service: "{{ item }}"
    state: enabled
  loop:
    - kubelet
    - kube-nodeport-services
  when: "'workers' in group_names"
- name: Server-setup | open necessary ports for control
  ansible.posix.firewalld:
    service: "{{ item }}"
    state: enabled
  loop:
    - kube-apiserver
    - etcd-client
    - etc-server
    - kubelet
    - kube-scheduler-secure
    - kube-controller-manager-secure
  when: "'control' in group_names"
- name: Server-setup | disable swap
  ansible.builtin.command:
    cmd: swapoff -a
  register: swapoff_out
  changed_when: swapoff_out.rc == 0
- name: Server-setup | Comment out the swap line in fstab
  ansible.builtin.lineinfile:
    path: /etc/fstab
    regexp: '^(.+swap.+)'
    backrefs: true
    line: '#\1'
- name: Server-setup | remount all to make sure fstab is correct
  ansible.builtin.command:
    cmd: mount -a # noqa: command-instead-of-module
  register: mount_out
  changed_when: mount_out.rc == 0
- name: Server-setup | reboot the server
  ansible.builtin.reboot:
